# https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/
#
# type                  string          none    External type (file, archive, archive-file, or git-repo)
# refreshPeriod 	duration        0       Refresh period (Examples: one day (24h), one week (168h), or four weeks (672h))

{{ $externals := dict -}}

{{- with $repo := "dandavison/delta" -}}
{{-   with $version := (gitHubLatestRelease $repo).GetTagName -}}
{{-     $_ := set $externals ".local/bin/delta" (dict
          "type" "archive-file"
          "url" (printf "https://github.com/%s/releases/download/%s/delta-%s-x86_64-unknown-linux-musl.tar.gz" $repo $version $version)
          "path" (printf "delta-%s-x86_64-unknown-linux-musl/delta" $version)
          "refreshPeriod" "168h")
-}}
{{-   end -}}
{{- end -}}

{{- with $repo := "hickford/git-credential-oauth" -}}
{{-   with $version := trimPrefix "v" (gitHubLatestRelease $repo).GetTagName -}}
{{-     $_ := set $externals ".local/bin/git-credential-oauth" (dict
          "type" "archive-file"
          "url" (printf "https://github.com/%s/releases/download/v%s/git-credential-oauth_%s_linux_amd64.tar.gz" $repo $version $version)
          "path" "git-credential-oauth"
          "refreshPeriod" "168h")
-}}
{{-   end -}}
{{- end -}}

{{- with $repo := "zellij-org/zellij" -}}
{{-   with $version := (gitHubLatestRelease $repo).GetTagName -}}
{{-     $_ := set $externals ".cache/chezmoi/tmp/zellij" (dict
          "type" "archive"
          "url" (printf "https://github.com/%s/releases/download/%s/zellij-x86_64-unknown-linux-musl.tar.gz" $repo $version)
          "refreshPeriod" "168h")
-}}
{{-   end -}}
{{- end -}}

{{- $externals | toYaml }}
".config/sz.env/lib/ble.sh.curl":
  type: "archive"
  url: "https://github.com/akinomyoga/ble.sh/releases/download/nightly/ble-nightly.tar.xz"
  refreshPeriod: "168h"

".config/sz.env/lib/delta.themes.gitconfig":
  type: "file"
  url: "https://raw.githubusercontent.com/dandavison/delta/refs/heads/main/themes.gitconfig"
  refreshPeriod: "168h"

".config/sz.env/lib/bash-preexec/bash-preexec.sh":
  type: "file"
  url: "https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh"
  refreshPeriod: "168h"

