# https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/
#
# The externals are checked based on the refreshPeriod whenever an `apply` (or `update`) operations run  
#
# The simplest form to update all externals:
# ```sh
# chezmoi apply --include externals
# ```
#
# Variable              Type            Default Description
# type                  string          none    External type (file, archive, archive-file, or git-repo)
# url                   string          none    URL
# refreshPeriod         duration        0       Refresh period (Examples: one day (24h), one week (168h), or four weeks (672h))
# executable            bool            false   Add executable_ attribute to file
# path                  string          none    Path to file in archive

{{ $defaultRefresh := "168h" -}}
{{- $externals := dict -}}

{{- with $repo := "zellij-org/zellij" -}}
{{-   with $version := (gitHubLatestRelease $repo).GetTagName -}}
{{-     $_ := set $externals ".cache/chezmoi/tmp/zellij" (dict
          "type" "archive-file"
          "url" (printf "https://github.com/%s/releases/download/%s/zellij-x86_64-unknown-linux-musl.tar.gz" $repo $version)
          "path" "zellij"
          "executable" true
          "refreshPeriod" $defaultRefresh
) -}}
{{-   end -}}
{{- end }}

{{- with $repo := "dandavison/delta" -}}
{{-   with $version := (gitHubLatestRelease $repo).GetTagName -}}
{{-     $_ := set $externals ".local/bin/delta" (dict
          "type" "archive-file"
          "url" (printf "https://github.com/%s/releases/download/%s/delta-%s-x86_64-unknown-linux-musl.tar.gz" $repo $version $version)
          "path" (printf "delta-%s-x86_64-unknown-linux-musl/delta" $version)
          "refreshPeriod" $defaultRefresh
) -}}
{{-   end -}}
{{- end -}}

{{- with $repo := "hickford/git-credential-oauth" -}}
{{-   with $version := trimPrefix "v" (gitHubLatestRelease $repo).GetTagName -}}
{{-     $_ := set $externals ".local/bin/git-credential-oauth" (dict
          "type" "archive-file"
          "url" (printf "https://github.com/%s/releases/download/v%s/git-credential-oauth_%s_linux_amd64.tar.gz" $repo $version $version)
          "path" "git-credential-oauth"
          "executable" true
          "refreshPeriod" $defaultRefresh
) -}}
{{-   end -}}
{{- end -}}

{{- with $repo := "extrawurst/gitui" -}}
{{-   with $version := (gitHubLatestRelease $repo).GetTagName -}}
{{-     $_ := set $externals ".local/bin/gitui" (dict
          "type" "archive-file"
          "url" (printf "https://github.com/%s/releases/download/%s/gitui-linux-x86_64.tar.gz" $repo $version)
          "path" "./gitui"
          "executable" true
          "refreshPeriod" $defaultRefresh
) -}}
{{-   end -}}
{{- end }}

{{- $externals | toYaml }}
".config/sz.env/lib/ble.sh.curl":
  type: "archive"
  url: "https://github.com/akinomyoga/ble.sh/releases/download/nightly/ble-nightly.tar.xz"
  refreshPeriod: "{{ $defaultRefresh }}"

".config/sz.env/lib/delta.themes.gitconfig":
  type: "file"
  url: "https://raw.githubusercontent.com/dandavison/delta/refs/heads/main/themes.gitconfig"
  refreshPeriod: "{{ $defaultRefresh }}"

".config/sz.env/lib/bash-preexec/bash-preexec.sh":
  type: "file"
  url: "https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh"
  refreshPeriod: "{{ $defaultRefresh }}"
